### ISSUE TITLE
Unable to debug and deploy my APP. 

### ISSUE THREAD

**Issue by Itagiba** [heroku/heroku-apps#141]
I have been having problems deploying an app with heroku. More details [here](http://stackoverflow.com/questions/41830774/unable-to-push-webpack-react-es6-webpack-boilerplate-to-heroku). Whenever I try to launch it on heroku I get a series of obscure errors I cannot resolve. For example I know that `code=H10` is because the APP is crashing, however it does not give me much to go on fixing:

```
2017-01-24T14:59:26.356757+00:00 app[web.1]:     at Module._compile (module.js:542:28)
2017-01-24T14:59:26.356757+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-24T14:59:26.356758+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-24T14:59:26.356759+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-01-24T14:59:26.356760+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-01-24T14:59:26.356760+00:00 app[web.1]:     at Module.runMain (module.js:604:10)
2017-01-24T14:59:26.356761+00:00 app[web.1]:     at run (bootstrap_node.js:394:7)
2017-01-24T14:59:26.356761+00:00 app[web.1]:     at startup (bootstrap_node.js:149:9)
2017-01-24T14:59:26.356762+00:00 app[web.1]:     at bootstrap_node.js:509:3
2017-01-24T14:59:26.438789+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-24T15:00:44.167922+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hjk-app.herokuapp.com request_id=19e88153-e4a8-4cc8-8326-14ad5aa46c5d fwd="94.119.64.4" dyno= connect= service= status=503 bytes=
2017-01-24T15:00:44.970799+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hjk-app.herokuapp.com request_id=3e5ea79e-8f91-4b33-a912-a2910a7f5bb8 fwd="94.119.64.4" dyno= connect= service= status=503 bytes=
2017-01-24T15:03:34.125258+00:00 heroku[slug-compiler]: Slug compilation started
2017-01-24T15:03:34.125268+00:00 heroku[slug-compiler]: Slug compilation finished
2017-01-24T15:03:34.446039+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-24T15:03:37.639160+00:00 heroku[web.1]: Starting process with command `node server.prod.js`
2017-01-24T15:03:40.427085+00:00 heroku[web.1]: Process exited with status 1
2017-01-24T15:03:40.330132+00:00 app[web.1]: App is running, server is listening on port 34845
2017-01-24T15:03:40.332984+00:00 app[web.1]: events.js:160
2017-01-24T15:03:40.332986+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-01-24T15:03:40.332986+00:00 app[web.1]:       ^
2017-01-24T15:03:40.332987+00:00 app[web.1]: 
2017-01-24T15:03:40.332987+00:00 app[web.1]: Error: listen EADDRINUSE :::34845
2017-01-24T15:03:40.332988+00:00 app[web.1]:     at Object.exports._errnoException (util.js:1026:11)
2017-01-24T15:03:40.332988+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:1049:20)
2017-01-24T15:03:40.332989+00:00 app[web.1]:     at Server._listen2 (net.js:1257:14)
2017-01-24T15:03:40.332989+00:00 app[web.1]:     at listen (net.js:1293:10)
2017-01-24T15:03:40.332990+00:00 app[web.1]:     at Server.listen (net.js:1389:5)
2017-01-24T15:03:40.332990+00:00 app[web.1]:     at EventEmitter.listen (/app/node_modules/express/lib/application.js:617:24)
2017-01-24T15:03:40.332991+00:00 app[web.1]:     at Object.<anonymous> (/app/server.prod.js:17:5)
2017-01-24T15:03:40.332991+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-24T15:03:40.332991+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-24T15:03:40.332992+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-24T15:03:40.449657+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-24T15:04:04.812354+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-24T15:04:07.738488+00:00 heroku[web.1]: Starting process with command `node server.prod.js`
2017-01-24T15:04:09.684291+00:00 app[web.1]: App is running, server is listening on port 8329
2017-01-24T15:04:09.687128+00:00 app[web.1]: events.js:160
2017-01-24T15:04:09.687130+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-01-24T15:04:09.687131+00:00 app[web.1]:       ^
2017-01-24T15:04:09.687131+00:00 app[web.1]: 
2017-01-24T15:04:09.687132+00:00 app[web.1]: Error: listen EADDRINUSE :::8329
2017-01-24T15:04:09.687133+00:00 app[web.1]:     at Object.exports._errnoException (util.js:1026:11)
2017-01-24T15:04:09.687133+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:1049:20)
2017-01-24T15:04:09.687134+00:00 app[web.1]:     at Server._listen2 (net.js:1257:14)
2017-01-24T15:04:09.687134+00:00 app[web.1]:     at listen (net.js:1293:10)
2017-01-24T15:04:09.687135+00:00 app[web.1]:     at Server.listen (net.js:1389:5)
2017-01-24T15:04:09.687136+00:00 app[web.1]:     at EventEmitter.listen (/app/node_modules/express/lib/application.js:617:24)
2017-01-24T15:04:09.687137+00:00 app[web.1]:     at Object.<anonymous> (/app/server.prod.js:17:5)
2017-01-24T15:04:09.687137+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-24T15:04:09.687138+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-24T15:04:09.687138+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-24T15:04:09.751685+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-24T15:04:09.742383+00:00 heroku[web.1]: Process exited with status 1
2017-01-24T15:04:15.891187+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hjk-app.herokuapp.com request_id=504f99fa-1c65-437c-a636-b5a9f9080f81 fwd="94.119.64.4" dyno= connect= service= status=503 bytes=
2017-01-24T15:04:16.862217+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hjk-app.herokuapp.com request_id=985a6075-43e6-405c-b019-bc23dc21f97e fwd="94.119.64.4" dyno= connect= service= status=503 bytes=
2017-01-24T15:12:31.991899+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-24T15:12:36.493922+00:00 heroku[web.1]: Starting process with command `node server.prod.js`
2017-01-24T15:12:40.335376+00:00 heroku[web.1]: Process exited with status 1
2017-01-24T15:12:40.239255+00:00 app[web.1]: App is running, server is listening on port 42014
2017-01-24T15:12:40.249778+00:00 app[web.1]: events.js:160
2017-01-24T15:12:40.249780+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-01-24T15:12:40.249781+00:00 app[web.1]:       ^
2017-01-24T15:12:40.249782+00:00 app[web.1]: 
2017-01-24T15:12:40.249782+00:00 app[web.1]: Error: listen EADDRINUSE :::42014
2017-01-24T15:12:40.249783+00:00 app[web.1]:     at Object.exports._errnoException (util.js:1026:11)
2017-01-24T15:12:40.249784+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:1049:20)
2017-01-24T15:12:40.249784+00:00 app[web.1]:     at Server._listen2 (net.js:1257:14)
2017-01-24T15:12:40.249786+00:00 app[web.1]:     at Server.listen (net.js:1389:5)
2017-01-24T15:12:40.249785+00:00 app[web.1]:     at listen (net.js:1293:10)
2017-01-24T15:12:40.249787+00:00 app[web.1]:     at EventEmitter.listen (/app/node_modules/express/lib/application.js:617:24)
2017-01-24T15:12:40.249787+00:00 app[web.1]:     at Object.<anonymous> (/app/server.prod.js:17:5)
2017-01-24T15:12:40.249788+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-24T15:12:40.249788+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-24T15:12:40.249789+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-24T15:12:40.353336+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-24T15:12:40.354284+00:00 heroku[web.1]: State changed from crashed to starting
2017-01-24T15:12:43.609362+00:00 heroku[web.1]: Starting process with command `node server.prod.js`
2017-01-24T15:12:46.319249+00:00 heroku[web.1]: Process exited with status 1
2017-01-24T15:12:46.260013+00:00 app[web.1]: App is running, server is listening on port 43239
2017-01-24T15:12:46.263911+00:00 app[web.1]: events.js:160
2017-01-24T15:12:46.263913+00:00 app[web.1]:       throw er; // Unhandled 'error' event
2017-01-24T15:12:46.263915+00:00 app[web.1]: 
2017-01-24T15:12:46.263914+00:00 app[web.1]:       ^
2017-01-24T15:12:46.263916+00:00 app[web.1]: Error: listen EADDRINUSE :::43239
2017-01-24T15:12:46.263919+00:00 app[web.1]:     at Server.listen (net.js:1389:5)
2017-01-24T15:12:46.263916+00:00 app[web.1]:     at Object.exports._errnoException (util.js:1026:11)
2017-01-24T15:12:46.263920+00:00 app[web.1]:     at Object.<anonymous> (/app/server.prod.js:17:5)
2017-01-24T15:12:46.263922+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-01-24T15:12:46.263917+00:00 app[web.1]:     at exports._exceptionWithHostPort (util.js:1049:20)
2017-01-24T15:12:46.263918+00:00 app[web.1]:     at Server._listen2 (net.js:1257:14)
2017-01-24T15:12:46.263921+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-01-24T15:12:46.263918+00:00 app[web.1]:     at listen (net.js:1293:10)
2017-01-24T15:12:46.263920+00:00 app[web.1]:     at EventEmitter.listen (/app/node_modules/express/lib/application.js:617:24)
2017-01-24T15:12:46.263921+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-01-24T15:12:46.341650+00:00 heroku[web.1]: State changed from starting to crashed
2017-01-24T15:12:56.502654+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=hjk-app.herokuapp.com request_id=29a2849e-9bb9-48ca-bc41-43733ad4fe67 fwd="94.119.64.22" dyno= connect= service= status=503 bytes=
2017-01-24T15:12:57.352819+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=hjk-app.herokuapp.com request_id=5630e1b0-ebe9-473b-a052-9110f12250dd fwd="94.119.64.22" dyno= connect= service= status=503 bytes=
2017-01-24T15:32:33.639769+00:00 heroku[run.4331]: Client connection closed. Sending SIGHUP to all processes
2017-01-24T15:32:34.193969+00:00 heroku[run.4331]: State changed from up to complete
2017-01-24T15:32:34.176978+00:00 heroku[run.4331]: Process exited with status 129

```

The above sounds like a port being used issue? My app is supposed to listen to port 5000 so why all these port numbers? I don't understand.

**Comment by ransombriggs** [comment]
@Itagiba could you file an issue at https://support.heroku.com ?  This issue tracker is for CLI issues only and you will be routed to the appropriate group that will be better able to help you on the support site.

**Comment by mttrs** [comment]
@Itagiba ,
Thanks for creating a support ticket. We'll check it. Let me close this issue.
