### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by c0** [heroku/heroku-apps#54]
I just installed the heroku toolbelt and ran `heroku create` on a fresh node app, but now I receive this error: `Unexpected token ...`. It seems like the spread operator isn't supported.

`~/.heroku/node_modules/heroku-app` is version `1.5.1`

`~/.heroku` has `node-4.2.1-darwin-x86`, and I noticed this lib is testing only 5.4 in travis.

Full error:
```
$ heroku create
heroku-cli: Installing core plugins.../Users/awright/.heroku/node_modules/heroku-apps/commands/features/index.js:17
    let longest = Math.max(...features.map(f => f.name.length));
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/awright/.heroku/node_modules/heroku-apps/index.js:45:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at [eval]:2:15
    at Object.exports.runInThisContext (vm.js:54:17)
heroku-cli: Installing core plugins (retrying).../Users/awright/.heroku/node_modules/heroku-apps/commands/features/index.js:17
    let longest = Math.max(...features.map(f => f.name.length));
                           ^^^
```

**Comment by ransombriggs** [comment]
@c0 As a quick fix you could delete `~/.heroku/node-4.2.1-darwin-x86` and run `heroku update` which will bump you up to `node-v5.7.1-darwin-x64` which should fix your immediate problem while I look at our node update code.

**Comment by c0** [comment]
@ransombriggs Thanks! That solved the issue. Please let me know if you need any more debug info from me. I wouldn't want new devs to run into the same issue.

**Comment by ransombriggs** [comment]
@c0 I do not need any more info at this time, you gave me enough info that I should be able to recreate, thanks!

**Comment by ransombriggs** [comment]
@c0 thanks for your bug report, I was able to recreate and shipped a fix to remove the spread operator yesterday so that other people do not encounter this issue.

**Comment by c0** [comment]
@ransombriggs Sweet! Thank you.
